name: pigpio
description: GPIO for raspberry pi using pigpio library (//abyz.me.uk/rpi/pigpio/).
version: 1.0.0
repository: https://github.com/cthurston/pigpio_dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  ffi:

dev_dependencies:
  ffigen: 1.2.0
  pedantic: ^1.9.2
  test: 

ffigen:
  name: LibPiGpio
  description: >-
    libpigpio: GPIO for Raspberry Pi
  output: 'lib/src/bindings.dart'
  headers:
    entry-points:
      - 'ffi/pigpio.h'
  
